Repository CMU-17313Q/nodebb-f25-sickfault, pull requests merged in 2025-09, with the labels that each got.

#20 Added resolved status fields to topics database (Task 6, Issue #12)
  RESOLVED_FIELDS_INTERFACE.md
  public/openapi/components/schemas/TopicObject.yaml
  public/src/client/search.js
  src/topics/data.js
  src/upgrades/4.3.3/add_resolved_fields_to_topics.js
  vendor/nodebb-theme-harmony-2.1.15/templates/partials/sidebar-left.tpl
  vendor/nodebb-theme-harmony-2.1.15/templates/search.tpl
Labels: backend

#23 Implement comprehensive search frontend for posts
  .mocharc.yml
  public/openapi/write/users/uid/exports/type.yaml
  public/src/client/search.js
  test/api.js
  test/utils.js
  vendor/nodebb-theme-harmony-2.1.15/templates/partials/sidebar-left.tpl
  vendor/nodebb-theme-harmony-2.1.15/templates/search.tpl
Labels: frontend

#30 Added resolved status fields to topics database (Task 6, Issue #12)
  RESOLVED_FIELDS_INTERFACE.md
  public/openapi/components/schemas/TopicObject.yaml
  src/topics/data.js
  src/upgrades/4.3.3/add_resolved_fields_to_topics.js
Labels: backend

#25 Posts search backend
  public/openapi/write.yaml
  public/openapi/write/search/posts.yaml
  src/api/search.js
  src/controllers/write/search.js
  src/posts/index.js
  src/posts/search.js
  src/routes/write/search.js
Labels: backend, api
